# libraries

# load packages ----------------------------------------------------------

# review packages and remove any that are not actually used in the code

# load required packages by category
library(tidyverse) # includes ggplot2, dplyr, tidyr, readr, etc.
library(ggpubr) # publication-ready plots
library(ggrepel) # non-overlapping text labels
library(ggdist) # visualizing distributions
library(lme4) # linear mixed models
library(lmerTest) # p-values for lmer
library(glmmTMB) # generalized linear mixed models
library(DHARMa) # model residual diagnostics
library(emmeans) # estimated marginal means
library(multcomp) # simultaneous inference
library(multcompView) # compact letter display
library(car) # Anova(), VIF(), etc.
library(vegan) # ordination, PERMANOVA
library(permute) # control for permutation schemes
library(lattice) # base plotting system for some model outputs
library(reshape) # legacy reshape tools (check if still needed)
library(colorspace) # function to darken colors
library(MetBrewer) # colors from painting at the NY Metropolitan Museum of Art
# (https://github.com/BlakeRMills/MetBrewer)
library(MoMAColors) # colors from painting at the NY Museum of Modern Art
# (https://github.com/BlakeRMills/MoMAColors)
library(grateful) # for citing packages
library(kableExtra) # for formatting tables
library(webshot2) # for saving html as images

# cite packages ----------------------------------------------------------

# create csl and bib files for citing packages in the supplementary information
suppressWarnings(
  grateful::cite_packages(
    out.format = "tex-fragment",
    out.dir = "supp-info",
    citation.style = "new-phytologist"
  )
)

# remove files generated by grateful; only want the csl and bib files
file.remove("supp-info/grateful-report.tex")
