---
title: "Arabidopsis Rodrigo"
author: "Lucía Martín"
date: "2025-07-28"
output: html_document
---

```{r library, echo = FALSE}

#cargamos los paquetes

library(lmerTest)
library(lsmeans)
library(ggplot2)
library(tidyr)
library(tidyverse)
library(vegan)
library(ggpubr)
library(ggrepel)
library(stats)
library(rmarkdown)
library(reshape)
library(dplyr)
library(multcomp)
library(permute)
library(lattice)
library(car)
library(glmmTMB)
library(DHARMa)
library(multcompView)

```

```{r VOCs, echo = FALSE}

### cargamos los datos como table

data <- read.csv(file = "lucia/VOCs.csv", h = T, sep = ";", na.strings = "NA") #general
data

head(data)
attach(data)

data$Gen <- as.factor(data$Gen)
data$PopGen <- as.factor(data$PopGen)
data$Treat <- as.factor(data$Treat)
data$ID = as.factor(data$ID)
data$population = as.factor(data$population)
data$Sum = as.numeric(data$Sum)
data$H_E = as.numeric(data$H_E)

```


```{r PERMANOVA composition general, echo = FALSE}

#factors
factors = data[, c(1:9)] #factors
str(factors) #deben estar como factores

#variables
VOCS = data[, c(10:26)]
VOCS[is.na(VOCS)] = 0 #Use zeros
str(VOCS) #Deben estar como numericos

#step1:create a distance matrix from the variable dataframe

VOCS.dist = vegdist(VOCS, method = 'bray')


#modelo con Gen anidado dentro de población como aleatorio
per2 = adonis2(
  formula = VOCS.dist ~ Treat * population,
  data = factors,
  permutations = 10000,
  strata = factors$PopGen,
  by = "terms"
) #aquí he creado una columna de PopGen en el data frame #porque adonis no acepta factores aleatorios anidados como un modelo mixto, así #que para que el modelo contemple este efecto se crea una columna nueva de interacción
per2

```

```{r PcoA Population composition, echo = FALSE}

#Unconstrained analysis

d.partial.pco.VOCS <- capscale(
  VOCS.dist ~ 1 + Condition(factors$Treat),
  data = factors,
  comm = VOCS
) #Conditioning on Treat (So ordination is performed after the Treat effect is accounted for/removed)

head(summary(d.partial.pco.VOCS))

d.eig.VOCS <- eigenvals(d.partial.pco.VOCS) ##extract eignevalues
d.eig.VOCS[1:3] / sum(d.eig.VOCS) #proportion of variance explained by each axis
cumsum(d.eig.VOCS[1:3] / sum(d.eig.VOCS)) #Same but cummulative

#Building the plot centroids for each treatment, unconstrained ordination
factors$ID = as.factor(factors$ID)

##Site ordination scores for MDS1 and MDS2 (for individuals/observations)
div.ind.VOCS <- data.frame(
  ID = rownames(d.partial.pco.VOCS$CA$u),
  treatment = factors$population,
  Plant = factors$ID,
  MDS1 = scores(d.partial.pco.VOCS, scaling = 3, correlation = TRUE)$sites[, 1],
  MDS2 = scores(d.partial.pco.VOCS, scaling = 3, correlation = TRUE)$sites[, 2]
)


##use envfit for fitted order arrows
#inertia is variance in species (volatiles) abundance/composition
bt.VOCS.div <- cbind(factors %>% dplyr::select(ID, population), VOCS)
env.VOCS.div <- envfit(d.partial.pco.VOCS, bt.VOCS.div)
env.VOCS.div #Pay attention here.
#VECTORS are the arrows
#FACTORS are the centroids
#rsq T is 0 because we removed it from the model in the PcoA
#We see the direction of the vector, the rsq and the p-value of each species (volatile)

div.cen.VOCS <- data.frame(
  T = rownames(env.VOCS.div$factors$centroids),
  MDS1 = env.VOCS.div$factors$centroids[, 1],
  MDS2 = env.VOCS.div$factors$centroids[, 2]
) %>%
  filter(T == 'populationB' | T == 'populationC') #Select centroids for herbivory

div.arrow.VOCS <- data.frame(
  order = rownames(env.VOCS.div$vectors$arrows),
  MDS1 = env.VOCS.div$vectors$arrows[, 1],
  MDS2 = env.VOCS.div$vectors$arrows[, 2],
  pval = env.VOCS.div$vectors$pvals,
  rsq = env.VOCS.div$vectors$r
) %>%
  subset(pval <= 0.05 & rsq > 0.6) #Select arrows above ce

div.arrow.VOCS

##axis labels with var explained
xlabel <- paste0(
  'MDS1 (',
  round(100 * cumsum(d.eig.VOCS / sum(d.eig.VOCS))[[1]], 2),
  '% of total variation)'
)
ylabel <- paste0(
  'MDS2 (',
  round(100 * (d.eig.VOCS[[2]] / sum(d.eig.VOCS)), 2),
  '% of total variation)'
)


###Here we put everything we computed together and build the plot.

#first step: Plot the observations (sites) scores

###site.Plot.div.VOCS

site.Plot.div.VOCS <- ggplot(div.ind.VOCS, aes(x = MDS1, y = MDS2)) +
  geom_jitter(aes(fill = treatment), shape = 21, size = 3, stroke = 0.8) +
  theme_classic() +
  scale_fill_manual(
    name = "",
    values = c("red", "grey"),
    labels = c("Bon", "Cai")
  ) +
  theme(axis.line = element_blank()) +
  geom_hline(aes(yintercept = 0), lty = 'dashed', size = 0.7) +
  geom_vline(aes(xintercept = 0), lty = 'dashed', size = 0.7) +
  labs(x = xlabel, y = ylabel)

site.Plot.div.VOCS

```

```{r Secondplot, echo = FALSE}

#con este código veo que VOCs son los que definen la variación

arrow.Plot.div.VOCS <- site.Plot.div.VOCS +
  geom_segment(
    data = div.arrow.VOCS,
    aes(
      x = 0,
      xend = MDS1 * as.numeric(rsq),
      y = 0,
      yend = MDS2 * as.numeric(rsq)
    ),
    arrow = arrow(length = unit(0.2, "cm")),
    colour = "black",
    size = 1
  ) +
  geom_text_repel(
    data = div.arrow.VOCS,
    aes(
      x = MDS1 * as.numeric(rsq),
      y = MDS2 * as.numeric(rsq),
      label = order,
      min.segment.length = unit(5, 'lines')
    )
  ) +
  # annotate("text", x=-0.2, y=0.40, label= "(Z)-??-farnesene")+
  theme(
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_text(size = 10)
  )

arrow.Plot.div.VOCS

#Second step. Plot the arrows

arrow.Plot.div.VOCS <- site.Plot.div.VOCS +
  geom_segment(
    data = div.arrow.VOCS,
    aes(
      x = 0,
      xend = MDS1 * as.numeric(rsq),
      y = 0,
      yend = MDS2 * as.numeric(rsq)
    ),
    arrow = arrow(length = unit(0.30, "cm")),
    colour = "black",
    size = 0.9
  ) +
  geom_text_repel(
    data = div.arrow.VOCS,
    aes(
      x = MDS1 * as.numeric(rsq),
      y = MDS2 * as.numeric(rsq),
      label = (" "),
      min.segment.length = unit(5, 'lines')
    )
  ) +
  annotate(
    "text",
    x = 1.1,
    y = 0.25,
    label = "Tridecane",
    size = 4,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 1.1,
    y = 0.12,
    label = "Dodecanal",
    size = 4,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 1.14,
    y = -0.11,
    label = "(E)-2-Methyl-2-butenal",
    size = 4,
    fontface = "bold"
  ) +
  theme(
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_text(size = 14)
  )

arrow.Plot.div.VOCS

```

```{r finalPLOT, echo = FALSE}
##Third step. add centroids for each irrigation treatment and 95% CI

Plot.div.VOCS <- arrow.Plot.div.VOCS +
  #This are centroids for ach treatment.
  geom_point(
    data = subset(div.cen.VOCS, T == "populationB"),
    aes(x = MDS1, y = MDS2),
    size = 3,
    pch = 23,
    lwd = 3,
    cex = 3,
    colour = "black",
    fill = "red",
    stroke = 0.8
  ) + #B
  geom_point(
    data = subset(div.cen.VOCS, T == "populationC"),
    aes(x = MDS1, y = MDS2),
    size = 3,
    pch = 23,
    lwd = 3,
    cex = 3,
    colour = "black",
    fill = "grey",
    stroke = 0.8
  ) + #C
  stat_ellipse(
    aes(group = treatment, lty = treatment),
    type = 'norm',
    level = .95,
    col = "black",
    size = 0.7
  ) +
  scale_linetype_manual(name = "", values = c(1, 2), labels = c("Bon", "Cai")) +
  theme(legend.position = 'right') +
  xlim(c(-1.6, 1.6)) +
  ylim(c(-1.6, 1.6)) +
  theme(
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_text(size = 14)
  )
#ggtitle("(a)")

Plot.div.VOCS

#save the pic
ggsave(
  Plot.div.VOCS,
  file = 'Figure VOCs PCoA Pop.tiff',
  width = 150,
  height = 100,
  units = 'mm',
  dpi = 300
)

```

```{r PcoA Treat composition, echo = FALSE}

#Unconstrained analysis

d.partial.pco.VOCS <- capscale(
  VOCS.dist ~ 1 + Condition(factors$population),
  data = factors,
  comm = VOCS
) #Conditioning on population (So ordination is performed after the population effect is accounted for/removed)

head(summary(d.partial.pco.VOCS))

d.eig.VOCS <- eigenvals(d.partial.pco.VOCS) ##extract eignevalues
d.eig.VOCS[1:3] / sum(d.eig.VOCS) #proportion of variance explained by each axis
cumsum(d.eig.VOCS[1:3] / sum(d.eig.VOCS)) #Same but cummulative

#Building the plot centroids for each treatment, unconstrained ordination
factors$ID = as.factor(factors$ID)

##Site ordination scores for MDS1 and MDS2 (for individuals/observations)
div.ind.VOCS <- data.frame(
  ID = rownames(d.partial.pco.VOCS$CA$u),
  treatment = factors$Treat,
  Plant = factors$ID,
  MDS1 = scores(d.partial.pco.VOCS, scaling = 3, correlation = TRUE)$sites[, 1],
  MDS2 = scores(d.partial.pco.VOCS, scaling = 3, correlation = TRUE)$sites[, 2]
)


##use envfit for fitted order arrows
#inertia is variance in species (volatiles) abundance/composition
bt.VOCS.div <- cbind(factors %>% dplyr::select(ID, Treat), VOCS)
env.VOCS.div <- envfit(d.partial.pco.VOCS, bt.VOCS.div)
env.VOCS.div #Pay attention here.
#VECTORS are the arrows
#FACTORS are the centroids
#rsq T is 0 because we removed it from the model in the PcoA
#We see the direction of the vector, the rsq and the p-value of each species (volatile)

div.cen.VOCS <- data.frame(
  T = rownames(env.VOCS.div$factors$centroids),
  MDS1 = env.VOCS.div$factors$centroids[, 1],
  MDS2 = env.VOCS.div$factors$centroids[, 2]
) %>%
  filter(T == 'Treatc' | T == 'Treath') #Select centroids for herbivory

div.arrow.VOCS <- data.frame(
  order = rownames(env.VOCS.div$vectors$arrows),
  MDS1 = env.VOCS.div$vectors$arrows[, 1],
  MDS2 = env.VOCS.div$vectors$arrows[, 2],
  pval = env.VOCS.div$vectors$pvals,
  rsq = env.VOCS.div$vectors$r
) %>%
  subset(pval <= 0.05 & rsq > 0.6) #Select arrows above ce

div.arrow.VOCS

##axis labels with var explained
xlabel <- paste0(
  'MDS1 (',
  round(100 * cumsum(d.eig.VOCS / sum(d.eig.VOCS))[[1]], 2),
  '% of total variation)'
)
ylabel <- paste0(
  'MDS2 (',
  round(100 * (d.eig.VOCS[[2]] / sum(d.eig.VOCS)), 2),
  '% of total variation)'
)


###Here we put everything we computed together and build the plot.

#first step: Plot the observations (sites) scores

#div.ind.VOCS$T <- factor(div.ind.VOCS$T, c("Q", "Q+B", "Q+P", "Q+B+P"))

###site.Plot.div.VOCS

site.Plot.div.VOCS <- ggplot(div.ind.VOCS, aes(x = MDS1, y = MDS2)) +
  geom_jitter(aes(fill = treatment), shape = 21, size = 3, stroke = 0.8) +
  theme_classic() +
  scale_fill_manual(
    name = "",
    values = c("mintcream", "mediumseagreen"),
    labels = c("Control", "Herbivory")
  ) +
  theme(axis.line = element_blank()) +
  geom_hline(aes(yintercept = 0), lty = 'dashed', size = 0.7) +
  geom_vline(aes(xintercept = 0), lty = 'dashed', size = 0.7) +
  labs(x = xlabel, y = ylabel)

site.Plot.div.VOCS

```

```{r Secondplot, echo = FALSE}

#con este código veo que VOCs son los que definen la variación

arrow.Plot.div.VOCS <- site.Plot.div.VOCS +
  geom_segment(
    data = div.arrow.VOCS,
    aes(
      x = 0,
      xend = MDS1 * as.numeric(rsq),
      y = 0,
      yend = MDS2 * as.numeric(rsq)
    ),
    arrow = arrow(length = unit(0.2, "cm")),
    colour = "black",
    size = 1
  ) +
  geom_text_repel(
    data = div.arrow.VOCS,
    aes(
      x = MDS1 * as.numeric(rsq),
      y = MDS2 * as.numeric(rsq),
      label = order,
      min.segment.length = unit(5, 'lines')
    )
  ) +
  # annotate("text", x=-0.2, y=0.40, label= "(Z)-??-farnesene")+
  theme(
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_text(size = 10)
  )

arrow.Plot.div.VOCS

#Second step. Plot the arrows

arrow.Plot.div.VOCS <- site.Plot.div.VOCS +
  geom_segment(
    data = div.arrow.VOCS,
    aes(
      x = 0,
      xend = MDS1 * as.numeric(rsq),
      y = 0,
      yend = MDS2 * as.numeric(rsq)
    ),
    arrow = arrow(length = unit(0.30, "cm")),
    colour = "black",
    size = 0.9
  ) +
  geom_text_repel(
    data = div.arrow.VOCS,
    aes(
      x = MDS1 * as.numeric(rsq),
      y = MDS2 * as.numeric(rsq),
      label = (" "),
      min.segment.length = unit(5, 'lines')
    )
  ) +
  annotate(
    "text",
    x = 1.1,
    y = 0.25,
    label = "Tridecane",
    size = 4,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 1.1,
    y = 0.15,
    label = "Dodecanal",
    size = 4,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 1.10,
    y = -0.09,
    label = "(E)-2-Methyl-2-butenal",
    size = 4,
    fontface = "bold"
  ) +
  theme(
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_text(size = 14)
  )

arrow.Plot.div.VOCS

```

```{r finalPLOT, echo = FALSE}
##Third step. add centroids for each irrigation treatment and 95% CI

Plot.div.VOCS <- arrow.Plot.div.VOCS +
  #This are centroids for ach treatment.
  geom_point(
    data = subset(div.cen.VOCS, T == "Treatc"),
    aes(x = MDS1, y = MDS2),
    size = 3,
    pch = 23,
    lwd = 3,
    cex = 3,
    colour = "black",
    fill = "mintcream",
    stroke = 0.8
  ) + #Control
  geom_point(
    data = subset(div.cen.VOCS, T == "Treath"),
    aes(x = MDS1, y = MDS2),
    size = 3,
    pch = 23,
    lwd = 3,
    cex = 3,
    colour = "black",
    fill = "mediumseagreen",
    stroke = 0.8
  ) + #herbivory
  stat_ellipse(
    aes(group = treatment, lty = treatment),
    type = 'norm',
    level = .95,
    col = "black",
    size = 0.7
  ) +
  scale_linetype_manual(
    name = "",
    values = c(1, 2),
    labels = c("Control", "Herbivory")
  ) +
  theme(legend.position = 'right') +
  xlim(c(-1.6, 1.6)) +
  ylim(c(-1.6, 1.6)) +
  theme(
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_text(size = 14)
  )
#ggtitle("(a)")

Plot.div.VOCS

#save the pic
ggsave(
  Plot.div.VOCS,
  file = 'Figure VOCs PCoA Treat.pop.tiff',
  width = 150,
  height = 100,
  units = 'mm',
  dpi = 300
)

```

#VOCs groups
```{r VOCs groups, echo = FALSE}

### cargamos los datos como table

data <- read.csv(file = "VOCdivision.csv", h = T, sep = ";", na.strings = "NA")
data

head(data)
attach(data)

data$Gen <- as.factor(data$Gen)
data$Treat <- as.factor(data$Treat)
data$ID = as.factor(data$ID)
data$population = as.factor(data$population)

data <- read.csv(file = "alkanes.csv", h = T, sep = ";", na.strings = "NA")
data

n_table <- data %>%
  group_by(Treat, population) %>%
  summarise(N = n(), .groups = "drop")

```



```{r normalidad, echo=FALSE}
str(data) #Que tipo de datos tengo
summary(data)

hist(data$Aromatic.compounds)
hist(sqrt(data$Aromatic.compounds))
hist(log(data$Aromatic.compounds))

hist(data$Alcohols.and.esters)
hist(sqrt(data$Alcohols.and.esters))
hist(log(data$Alcohols.and.esters))

hist(data$GLVs)
hist(sqrt(data$GLVs))
hist(log(data$GLVs))

hist(data$Long.chain.alkanes)
hist(sqrt(data$Long.chain.alkanes))
hist(log(data$Long.chain.alkanes))

hist(data$Monoterpenes)
hist(sqrt(data$Monoterpenes))
hist(log(data$Monoterpenes))
```

```{r MODELOs VOCs grupos, echo=FALSE}

#efecto tratamientio

#Aromatic.compounds: Acetophenone
lme = lmer(
  sqrt(Aromatic.compounds) ~ Treat * population + (1 | population:Gen),
  data = data
)
anova(lme) #me quedo con este

summary(lme)
resid(lme)
shapiro.test(resid(lme))
hist(resid(lme))

modelo2 <- glmmTMB(
  Aromatic.compounds ~ Treat * population + (1 | population:Gen),
  data = data,
  family = ziGamma(link = "log"),
  ziformula = ~1
)

Anova(modelo2, type = "III")
summary(modelo2)

modelo2 <- glmmTMB(
  Aromatic.compounds ~ Treat * population + (1 | population:Gen),
  family = glmmTMB::tweedie(link = "log"),
  data = data
)

Anova(modelo2, type = "III")

sim_res <- simulateResiduals(fittedModel = modelo2)
plot(sim_res)
testResiduals(sim_res)
testDispersion(sim_res)
testZeroInflation(sim_res)

#GLVs
lme = lmer(
  sqrt(GLVs) ~ H_E + Treat * population + (1 | population:Gen),
  data = data
)
anova(lme)

summary(lme)
resid(lme)
shapiro.test(resid(lme))
hist(resid(lme))

modelo2 <- glmmTMB(
  GLVs ~ Treat * population + (1 | population:Gen),
  data = data,
  family = ziGamma(link = "log"),
  ziformula = ~1
) #me quedo con este

Anova(modelo2, type = "III")
summary(modelo2)


sim_res <- simulateResiduals(fittedModel = modelo2)
plot(sim_res)
testResiduals(sim_res)
testDispersion(sim_res)
testZeroInflation(sim_res)

#Monoterpenes
lme = lmer(
  Monoterpenes ~ H_E + Treat * population + (1 | population:Gen),
  data = data
)
anova(lme)

summary(lme)
resid(lme)
shapiro.test(resid(lme))
hist(resid(lme))

modelo2 <- glmmTMB(
  Monoterpenes ~ Treat * population + (1 | population:Gen),
  data = data,
  family = ziGamma(link = "log"),
  ziformula = ~1
) #me quedo con este

Anova(modelo2, type = "III")
summary(modelo2)


sim_res <- simulateResiduals(fittedModel = modelo2)
plot(sim_res)
testResiduals(sim_res)
testDispersion(sim_res)
testZeroInflation(sim_res)

# Long chain alkanes
lme = lmer(
  log(Long.chain.alkanes + 1) ~ H_E + Treat * population + (1 | population:Gen),
  data = data
)
anova(lme)

summary(lme)
resid(lme)
shapiro.test(resid(lme))
hist(resid(lme))

modelo3 <- glmmTMB(
  Long.chain.alkanes ~ Treat * population + (1 | population:Gen),
  data = data,
  family = ziGamma(link = "log"),
  ziformula = ~1
) #me quedo con este

Anova(modelo3, type = "III")
summary(modelo3)

sim_res <- simulateResiduals(fittedModel = modelo2)
plot(sim_res)
testResiduals(sim_res)
testDispersion(sim_res)
testZeroInflation(sim_res)

#Alcohols and esters
lme = lmer(
  sqrt(Alcohols.and.esters) ~ Treat * population + (1 | population:Gen),
  data = data
)
anova(lme) #me quedo con este

summary(lme)
resid(lme)
shapiro.test(resid(lme))
hist(resid(lme))

modelo2 <- glmmTMB(
  Alcohols.and.esters ~ H_E + Treat * population + (1 | population:Gen),
  data = data,
  family = ziGamma(link = "log"),
  ziformula = ~1
)

Anova(modelo2, type = "III")
summary(modelo2)

sim_res <- simulateResiduals(fittedModel = modelo2)
plot(sim_res)
testResiduals(sim_res)
testDispersion(sim_res)
testZeroInflation(sim_res)

```


```{r medias grupos, echo=FALSE}
lsmeansglv = as.data.frame(lsmeans(
  modelo2,
  pairwise ~ Treat,
  adjustSigma = TRUE,
  adjust = "tukey",
  type = "response"
))

lsmeanslongchain = as.data.frame(lsmeans(
  modelo3,
  pairwise ~ Treat | population,
  adjustSigma = TRUE,
  adjust = "tukey",
  type = "response"
))

lsmeansglvs = lsmeans(
  modelo2,
  pairwise ~ Treat | population,
  adjustSigma = TRUE,
  adjust = "tukey"
) # tukey test

lsmeansglongchain = lsmeans(
  modelo3,
  pairwise ~ Treat | population,
  adjustSigma = TRUE,
  adjust = "tukey"
) # tukey test

lsmeans_result.glvs <- lsmeans(
  modelo2,
  pairwise ~ Treat | population,
  adjustSigma = TRUE,
  adjust = "tukey",
  type = "response"
)

cld(lsmeans_result.glvs)

lsmeans_result.longchain <- lsmeans(
  modelo3,
  pairwise ~ Treat | population,
  adjustSigma = TRUE,
  adjust = "tukey",
  type = "response"
)

cld(lsmeans_result.longchain)


library(openxlsx) #guardamos en excel
write.xlsx(lsmeansglv, "lsmeansglv.xlsx")
write.xlsx(lsmeanslongchain, "lsmeanslongchain.xlsx")
```


```{r Long chain alkanes, echo=FALSE}
lsmeanse = as.data.frame(lsmeans(
  modelo2,
  pairwise ~ Treat | population,
  adjustSigma = TRUE,
  adjust = "tukey",
  type = "response"
))

lsmeans = lsmeans(
  modelo2,
  pairwise ~ Treat | population,
  adjustSigma = TRUE,
  adjust = "tukey"
) # tukey test

lsmeans_result <- lsmeans(
  modelo2,
  pairwise ~ Treat | population,
  adjustSigma = TRUE,
  adjust = "tukey",
  type = "response"
)

cld(lsmeans_result)

library(openxlsx) #guardamos en excel
write.xlsx(lsmeanse, "lsmeans fatty acids.xlsx")

```


```{r Plot Alkanes emittersxpopulation, echo=FALSE}

data1 <- read.csv(
  file = "lsmeanslongchain.csv",
  h = T,
  sep = ";",
  na.strings = "NA"
)

data1

data1$population <- factor(data1$population, levels = c("Bon", "Cai"))
data1$Treat <- factor(data1$Treat, levels = c("c", "h"))

plotE <- ggplot(data1, aes(x = population, y = lsmean, fill = Treat)) +
  geom_bar(
    stat = "identity",
    position = position_dodge(0.8), # Separa barras por tratamiento
    width = 0.7,
    color = "black",
    linewidth = 0.5
  ) +
  geom_errorbar(
    aes(ymin = lsmean - SE, ymax = lsmean + SE),
    width = 0.2,
    position = position_dodge(0.8) # Alinea con las barras
  ) +
  labs(
    x = "Population",
    y = "Long chain alkanes emission (ng/h)",
    fill = "Emitter treatment"
  ) +
  scale_fill_manual(
    values = c("c" = "mintcream", "h" = "mediumseagreen"),
    labels = c("c" = "Control", "h" = "Herbivore-induced")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = "top"
  )

plotE

ggsave(
  plotE,
  file = 'FIGURE long chain alkanes.tiff',
  width = 150,
  height = 100,
  units = 'mm',
  dpi = 300
)

```
